### ISSUE TITLE
build is broken 6f53a88 91dd28f

### ISSUE THREAD

**Issue by rookytilasiniai** [binance-exchange/binance-java-api#103]
build fails to compile:

AllAssets.java:[98,13] incompatible types: boolean cannot be converted to long

Merge: 6f53a88 91dd28f
Author: João Silva <joao.pcg.silva@gmail.com>
Date:   Mon Mar 26 00:34:55 2018 +0200

    Merge pull request #98 from TobCar/master
    
    Add support for AllAssets.

**Comment by joaopsilva** [comment]
Hi @rookytilasiniai, this is now fixed.
