### ISSUE TITLE
Binance REST API Executed price

### ISSUE THREAD

**Issue by personalityson** [binance-exchange/binance-java-api#104]
Hi, It is now apparent to me: Literally every other exchange has, but not Binance.
Is it not possible to retrieve average price for a specific limit order?

It is possible for market orders with response type = full, but for limit orders you need to search through recent trades...

If the order is old, this becomes impossible. How do you know from which trade id to seach?

Binance http api has something called tradeOrders which shows 20 last orders with executedPrice, delegateMoney etc. Why not make the same available through REST API?

On top of this, why can I not create issues in https://github.com/binance-exchange/binance-official-api-docs ?

**Comment by joaopsilva** [comment]
Hi, indeed, that is currently not supported. The `tradeOrders` API is private at the moment, and I am not aware of any upcoming change which would make it available through the REST API.

As for the docs, they are not meant to be a place for raising feature requests, those should be addressed you can try to reach out the team on Telegram (@binance_api_english) for that.
