### ISSUE TITLE
Impossible to check real buy price

### ISSUE THREAD

**Issue by luxel1103** [binance-exchange/binance-java-api#105]
Hello,

When i want to buy for example 1 ethereum for 0.055 bitcoin with a limitBuy while the actual price on binance is 0.0549 bitcoin, the order will buy 1 ethereum for 0.0549 instead of 0.055.

Now we can receive the order information and buy price with: 
`Order order = client.getOrderStatus(new OrderStatusRequest(symbol,"12345L"));
String buyPrice = order.getBuyPrice();`

At this moment the buyPrice is 0.055 instead of 0.0549 and there seems to be no way to receive the real buy price from this order.

Is there an other way to receive this information or is this not possible with this API?

**Comment by personalityson** [comment]
It's impossible because their API is shitty
https://github.com/binance-exchange/binance-java-api/issues/104

**Comment by luxel1103** [comment]
You can get the real buy price from this list of order fills:

`{
  "symbol": "BTCUSDT",
  "orderId": 28,
  "clientOrderId": "6gCrw2kRUAF9CvJDGP16IP",
  "transactTime": 1507725176595,
  "price": "0.00000000",
  "origQty": "10.00000000",
  "executedQty": "10.00000000",
  "status": "FILLED",
  "timeInForce": "GTC",
  "type": "MARKET",
  "side": "SELL",
  "fills": [
    {
      "price": "4000.00000000",
      "qty": "1.00000000",
      "commission": "4.00000000",
      "commissionAsset": "USDT"
    },
    {
      "price": "3999.00000000",
      "qty": "5.00000000",
      "commission": "19.99500000",
      "commissionAsset": "USDT"
    },
    {
      "price": "3998.00000000",
      "qty": "2.00000000",
      "commission": "7.99600000",
      "commissionAsset": "USDT"
    },
    {
      "price": "3997.00000000",
      "qty": "1.00000000",
      "commission": "3.99700000",
      "commissionAsset": "USDT"
    },
    {
      "price": "3995.00000000",
      "qty": "1.00000000",
      "commission": "3.99500000",
      "commissionAsset": "USDT"
    }
  ]
}`

But if you use this API, there is no list with Fills in the Order object.

**Comment by Willthegod** [comment]
@luxel1103  Just found out it does not support list with Fills, trying to add it myself now lol

**Comment by luxel1103** [comment]
@Willthegod Please let me know if you succeed in this, would be interested in the code for that.
