### ISSUE TITLE
Strange warning given

### ISSUE THREAD

**Issue by pantoea** [binance-exchange/binance-java-api#107]
okhttp3.internal.platform.Platform log
WARNING: A connection to https://stream.binance.com:9443/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

Anyone else seeing this ?

**Comment by joaopsilva** [comment]
Hi @pantoea , I'm unable to reproduce this, please provide a working example and I can have a second look. Thanks.

**Comment by weichafe** [comment]
I have the same problem, someone knows how to solve it
