### ISSUE TITLE
Dependency not working

### ISSUE THREAD

**Issue by Horray** [binance-exchange/binance-java-api#109]
I'm trying to use the binance Java API. When I add:

`Implementation: 'com. binance.api: binance-api-client: 1.0.0'`

to the dependendencies and sync it, I get an error saying, `Failed to resolve: com.binance.api:binance-api-client:1.0.0`

What am I doing wrong and how can I fix it?

**Comment by kfuksman** [comment]
+1

**Comment by h-e-n-r-y** [comment]
You need to build the maven artifact yourself.
- clone this git repo
- change to the directory
- issue a mvn install

```
git clone https://github.com/binance-exchange/binance-java-api.git
cd binance-java-api
mvn install
```

After that the dependency can be resolved through you local maven repository.

**Comment by kfuksman** [comment]
Yes I know that I can do this, but isn't the best solution.  Will be more usable if it's in maven repository

**Comment by joaopsilva** [comment]
Hi @kfuksman , yes, this will be available soon, in the meantime, please install it locally.

**Comment by WrongJuice** [comment]
Is it available now ?
