### ISSUE TITLE
Does the API support fill callback ?

### ISSUE THREAD

**Issue by szd116** [binance-exchange/binance-java-api#111]
First, thank you for this great api, its very easy to use and pretty fast too. I have a quick question, 1. How do i listen for fills/partial fills 2. how do I capture rejects and unsolicited cancel ? 
thank you again for this great api.

**Comment by joaopsilva** [comment]
Hi @szd116 , glad you've figured it out. Indeed, to listen to real-time updates, you need to rely on the web socket client.
