### ISSUE TITLE
WebSockect 24hr Individual Symbol

### ISSUE THREAD

**Issue by deluxeuo** [binance-exchange/binance-java-api#113]
Hello friends!

Is there any websocket for a specific currency?
I did not find it

**Comment by monkeyden** [comment]
Did you look at the examples?  Just do what he's doing here:
[CandlesticksCacheExample.java](https://github.com/binance-exchange/binance-java-api/blob/master/src/test/java/com/binance/api/examples/CandlesticksCacheExample.java)

`CandlesticksCacheExample("ETHUSDT", CandlestickInterval.ONE_MINUTE)`
