### ISSUE TITLE
client.onAllMarketTickersEvent(response -> System.out.println(response.get(0).getSymbol())); not working

### ISSUE THREAD

**Issue by eeyhp2** [binance-exchange/binance-java-api#114]
Hi, 

I cannot access any of the methods relating to AllMarketTickersEvent. Please help, Code being used is:

`wsclient.onAllMarketTickersEvent(response -> System.out.println(response.get(0).getSymbol()));`

Thanks.

**Comment by mjwchapman** [comment]
Add a try/catch and you'll see a class cast exception, see here: https://github.com/binance-exchange/binance-java-api/issues/72
