### ISSUE TITLE
多线程，感觉会造成apikey混用

### ISSUE THREAD

**Issue by gMan1990** [binance-exchange/binance-java-api#119]
https://github.com/binance-exchange/binance-java-api/blob/69f56f5fcfc8aadf00fdbfe38cd0aaec80aa6da8/src/main/java/com/binance/api/client/impl/BinanceApiServiceGenerator.java#L35
```
public synchronized static <S> S createService
```

* 只要使用不同的apikey 一直newRestClient(),
断点到createService方法里面的httpClient.addInterceptor(interceptor);
进入观察interceptors变量就会发现 这个list里面的内容一直在增加
* private static Retrofit.Builder builder
这个变量同样有问题，在builder.client(httpClient.build());的地方
* private static Retrofit retrofit
这3个静态的变量感觉都有线程安全问题

**Comment by gMan1990** [comment]
提bug会有bnb之类的奖励么？？？（紧张~

**Comment by joaopsilva** [comment]
Duplicate of #99.
