### ISSUE TITLE
Account has insufficient balance for requested action.

### ISSUE THREAD

**Issue by huykn** [binance-exchange/binance-java-api#120]
tracelog:
`
com.binance.api.client.exception.BinanceApiException: Account has insufficient balance for requested action. at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:57) at com.binance.api.client.impl.BinanceApiRestClientImpl.newOrder(BinanceApiRestClientImpl.java:130)`

Request order:`
{"price":"14.107","quantity":"1.000","recvWindow":6000000,"side":"BUY","symbol":"BNBUSDT","timeInForce":"GTC","timestamp":1524763355419,"type":"LIMIT"}`

Error AssetBalance
`BNB AssetBalance[asset=BNB,free=0.00000000,locked=0.00000000] USDT: AssetBalance[asset=USDT,free=0.00000000,locked=0.00000000]`

My account:
<img width="663" alt="screen shot 2018-04-27 at 12 25 11 am" src="https://user-images.githubusercontent.com/11696396/39321664-da598a5c-49b1-11e8-91bf-0c8cf76a9c7a.png">

Always tracelog: Account has insufficient balance for requested action.
Please help me!!!

**Comment by huykn** [comment]
issue when create restapi twice times

**Comment by rw026** [comment]
What do you mean by creating rest api twice? Is there a way to close it?
I run into the same problem but only creating the restapi once...
