### ISSUE TITLE
No Multi-tenancy possible?

### ISSUE THREAD

**Issue by BadRookiDev** [binance-exchange/binance-java-api#123]
No code needed to describe the problem.
I can't find out how to use multiple restClients, all clients will use the keys of the first client.

**Comment by bmschwartz** [comment]
Yea unfortunately not. Someone addressed this in another issue.

https://github.com/binance-exchange/binance-java-api/issues/99

**Comment by joaopsilva** [comment]
Hi @BadRookiDev , I'll look into this. It was also mentioned already in #99. Please follow-up in there. Thanks.
