### ISSUE TITLE
[bug] two ENDPOINT_SECURITY_TYPE_SIGNED?

### ISSUE THREAD

**Issue by gMan1990** [binance-exchange/binance-java-api#127]
https://github.com/binance-exchange/binance-java-api/blob/eb1ff5ca108082087a226989d4c70f82389f13b2/src/main/java/com/binance/api/client/security/AuthenticationInterceptor.java#L36
```
newRequestBuilder.removeHeader(BinanceApiConstants.ENDPOINT_SECURITY_TYPE_SIGNED)
            .removeHeader(BinanceApiConstants.ENDPOINT_SECURITY_TYPE_SIGNED);
```

**Comment by joaopsilva** [comment]
Thanks @gMan1990 , well spotted.
