### ISSUE TITLE
can use javax.xml.bind.DatatypeConverter

### ISSUE THREAD

**Issue by gMan1990** [binance-exchange/binance-java-api#128]
1.
https://github.com/binance-exchange/binance-java-api/blob/a00fa6ebc4306f0bdebd140cb9ec067a2c354085/src/main/java/com/binance/api/client/security/HmacSHA256Signer.java#L24
```
byte[] doFinal = sha256_HMAC.doFinal(message.getBytes());
return DatatypeConverter.printHexBinary(doFinal);
```
So commons-codec is not need in pom.xml.
Or commons-codec is better?(performance?  i don't know)

2.
https://github.com/binance-exchange/binance-java-api/blob/a00fa6ebc4306f0bdebd140cb9ec067a2c354085/src/main/java/com/binance/api/client/BinanceApiRestClient.java#L30
façade ? (french
facade ? (english

**Comment by joaopsilva** [comment]
Hi @gMan1990 , commons-codec is helpful for this kind of library.

For 2) yes, both are valid (https://en.wikipedia.org/wiki/Facade_pattern).

**Comment by gMan1990** [comment]
**Got:** The DataTypeConverter class is supplied with JAXB library. This is part of the standard library until Java 8. Starting from Java 9, we need to add java.xml.bind module to the runtime explicitly.
https://www.baeldung.com/java-byte-arrays-hex-strings
