### ISSUE TITLE
Questions about Stream API

### ISSUE THREAD

**Issue by cowwoc** [binance-exchange/binance-java-api#13]
Looking at https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md which your API mirrors,

1. What is the meaning of "Is the buyer the market maker?" I understand the concept of a maker vs taker, but what is the meaning of "*the* market maker" and what does this change for us if the value is true?

2. How can an aggregated trade event contain a single price/quantity value when it spans multiple trades? Are the trades guaranteed to be at the same price? Similarly, how can you only have a single trade-time across multiple trades?

**Comment by VaultDeveloper** [comment]
1. You can display in a different way if you know who is the maker/taker. For example, on the Binance Web UI, it says market if it's true and Limit if not.

**Comment by joaopsilva** [comment]
2. Yes, it's the aggregated trades at the price returned by the API. For mor details, you can check the aggTrades REST API, which describes it better: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md

**Comment by cowwoc** [comment]
@joaopsilva I looked at https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#compressedaggregate-trades-list but it does not explain how a single price is derived from multiple trades having potentially different prices...?
