### ISSUE TITLE
How can i list all open orders ? 

### ISSUE THREAD

**Issue by Eldenayri** [binance-exchange/binance-java-api#130]
In the first place thank you so much for this awesome API. In the second place i have a stupid question but i couldn't fix it by myself. i am really sorry for this stupid question. i wanna list all active open orders and trade history, not only just for "LINKETH", or not only just for other pairs. Can i list all open orders and trade history for all coins with little change in coding or i have to send separately request for all coin pairs? 

 " // Getting list of open orders
    List<Order> openOrders = client.getOpenOrders(new OrderRequest("LINKETH"));
    System.out.println(openOrders);"

**Comment by leechguy** [comment]
Try:
`` List<Order> orders = client.getOpenOrders(new OrderRequest(null));``

**Comment by Eldenayri** [comment]
ups. It works. Thank you so much.
