### ISSUE TITLE
How to list all order history without filtered with coin pairs? 

### ISSUE THREAD

**Issue by Eldenayri** [binance-exchange/binance-java-api#135]
Hi everyone. i wanna list my last 10 orders without filtered with coin pairs. How can i do that? "null" instead of "LINKETH" doesn't work. Thank you in advance for any help you can provide. 

    ` // Getting list of all orders with a limit of 10`
    ` List<Order> allOrders = client.getAllOrders(new AllOrdersRequest("LINKETH").limit(10));` 
    ` System.out.println(allOrders);`

**Comment by joaopsilva** [comment]
It's not possible at the moment. It's a limitation of the server API.

**Comment by elkceo** [comment]
> It's not possible at the moment. It's a limitation of the server API.

Is that possible now?
