### ISSUE TITLE
Cancel order returning void

### ISSUE THREAD

**Issue by matejsp** [binance-exchange/binance-java-api#136]
Cancel order is not returning an object.

According to rest api it should return:
{
  "symbol": "LTCBTC",
  "origClientOrderId": "myOrder1",
  "orderId": 1,
  "clientOrderId": "cancelMyOrder1"
}

current function:
void cancelOrder(CancelOrderRequest cancelOrderRequest);
it could be:
CancelOrderRequest cancelOrder(CancelOrderRequest cancelOrderRequest);

**Comment by joaopsilva** [comment]
This is now fixed, please update your repo.
