### ISSUE TITLE
Test binance java api, but got read time out

### ISSUE THREAD

**Issue by kjiao** [binance-exchange/binance-java-api#140]
Hello, 
I want to use binance java api,  and i made a simple test just to show server time with the example in the wiki. But I got 
Exception in thread "main" com.binance.api.client.exception.BinanceApiException: java.net.SocketTimeoutException: Read timed out at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:60)

the code is:
	BinanceApiClientFactory factory = BinanceApiClientFactory.newInstance(apikey, skey);
        BinanceApiRestClient client = factory.newRestClient();
        long serverTime = client.getServerTime();
        System.out.println(serverTime);

Do I need to configure something to make this work?
Thank you

**Comment by alexey-v777** [comment]
Try to use a proxy:

        System.setProperty("https.proxyHost", "<server>");
        System.setProperty("https.proxyPort", "<port>");

**Comment by joaopsilva** [comment]
I'm unable to reproduce your problem, but it seems like a firewall issue.
