### ISSUE TITLE
How to sell max amount at market price

### ISSUE THREAD

**Issue by pepenuyeg** [binance-exchange/binance-java-api#141]
Is there any way to sell, at market price, 100% of my asset balance using Java API?
 
Web interface has "100%" button that give me max amount i can sell. I'm looking for the same feature in the Java API.
 
Some examples:
 
I have 1383.84 ADA/ETH -> I can sell 1383
I have 0.7633 BNB/ETH -> I can sell 0.76
I have 9.99 AION/ETH -> I can sell 9.99
I have 235.0694 XRP/USDT -> I can sell 235.06
 
I would something like assetBalance.getMaxAmountICanSell().
 
Is there any way to do this?

**Comment by hadiAM** [comment]
you have to do it yourself, here some example :
```

 ExchangeInfo exchangeInfo = client.getExchangeInfo(); 
 SymbolInfo symbolInfo = exchangeInfo.getSymbolInfo( getSymbol() );  
 SymbolFilter lotFilter = symbolInfo.getSymbolFilter(FilterType.LOT_SIZE);  
 stepSize = new BigDecimal(lotFilter.getStepSize()).stripTrailingZeros().scale(); 
 String freeAsset = client.getAccount().getAssetBalance(getAssetSymbol().toUpperCase()).getFree(); 
 freeAsset = String.valueOf( roundFloor(Double.parseDouble( freeAsset ), getStepSize() ) ); 
 client.newOrder(marketSell( getSymbol(), freeAsset  ) ); 
```



* freeAsset must be rounded to "**floor**"

roundFloor method: 


```
public double roundFloor(double value, int places) {
        if (places < 0) 
            throw new IllegalArgumentException();
    
        BigDecimal bd = new BigDecimal(value);
        bd = bd.setScale(places, RoundingMode.FLOOR);
        return bd.doubleValue();
    }

```

**Comment by joaopsilva** [comment]
Indeed, please follow the example of @hadiAM (and double-check it before using).

**Comment by Grimmjawe** [comment]
> Is there any way to sell, at market price, 100% of my asset balance using Java API?
> 
> Web interface has "100%" button that give me max amount i can sell. I'm looking for the same feature in the Java API.
> 
> Some examples:
> 
> I have 1383.84 ADA/ETH -> I can sell 1383 I have 0.7633 BNB/ETH -> I can sell 0.76 I have 9.99 AION/ETH -> I can sell 9.99 I have 235.0694 XRP/USDT -> I can sell 235.06
> 
> I would something like assetBalance.getMaxAmountICanSell().
> 
> Is there any way to do this?


```
def roundStep(qty, stepSize): # Function round
  qty = decimal.Decimal(str(qty))
  return float(qty - qty % decimal.Decimal(str(stepSize)))

client = binance.Client(api_key='', api_secret='') # Client

symb_info = client.get_symbol_info('BTCEUR')["filters"] # Decimal Info
btc_balance = client.get_asset_balance(asset='BTC')['free'] # Balance
qty = roundStep(btc_balance, symb_info[2]["stepSize"]) # Round by decimal Info
client.order_market_sell(symbol='BTCEUR'l, quantity=qty)
```
