### ISSUE TITLE
Unrecognized field "isWorking"

### ISSUE THREAD

**Issue by JimmyUA** [binance-exchange/binance-java-api#143]
сom.binance.api.client.exception.BinanceApiException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "isWorking" (class com.binance.api.client.domain.account.Order), not marked as ignorable (13 known properties: "executedQty", "orderId", "time", "status", "icebergQty", "origQty", "side", "symbol", "timeInForce", "type", "clientOrderId", "stopPrice", "price"])
 at [Source: okhttp3.ResponseBody$BomAwareReader@1205687b; line: 1, column: 302] (through reference chain: com.binance.api.client.domain.account.Order["isWorking"])
	at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSynс

**Comment by joaopsilva** [comment]
Hi @JimmyUA , please update to the latest version. This is already fixed.
