### ISSUE TITLE
 binanceApiService.getServerTime().equal(new BinanceApiCallbackAdapter<>(callback));

### ISSUE THREAD

**Issue by donaldyang** [binance-exchange/binance-java-api#15]
BinanceApiAsyncRestClientImpl.java
line 52 write a wrong method,equeue  wrong to ‘equal()’
` @Override
  public void getServerTime(BinanceApiCallback<ServerTime> callback) {
    binanceApiService.getServerTime().enqueue(new BinanceApiCallbackAdapter<>(callback));
  }`

**Comment by joaopsilva** [comment]
Hi @donaldyang, could you please update your repository? This was fixed a few days ago.
