### ISSUE TITLE
Is BinanceApiRestClient and BinanceApiWebSocketClient (java) thread-safe and can I use as singleton?

### ISSUE THREAD

**Issue by Gilianp** [binance-exchange/binance-java-api#150]
Is BinanceApiRestClient and BinanceApiWebSocketClient thread safe? Can I use same instance to make several request at the same time and in multiple threads without any synchronization of my side?

**Comment by big-andy-coates** [comment]
I believe so, but the best thing to do is to test it!

**Comment by joaopsilva** [comment]
It is now yes, please update your repo.
