### ISSUE TITLE
Adding drivers

### ISSUE THREAD

**Issue by JelleGeers** [binance-exchange/binance-java-api#153]
How do you add drivers in the project to use?
I'm trying to add derbyClient but have no idea where to add it because there are no libraries.

**Comment by joaopsilva** [comment]
Hi @JelleGeers , I'm not quite sure I understand your question. You can install this library locally with `mvn install` and then import it in your project by including it in your `pom.xml` or `build.gradle`, for Maven, and Gradle, respectively.
