### ISSUE TITLE
API changes 2018-07-18

### ISSUE THREAD

**Issue by brintal** [binance-exchange/binance-java-api#155]
Is there any plan to incorporate the recent changes to the API?
https://github.com/binance-exchange/binance-official-api-docs/blob/master/CHANGELOG.md

I will try to make the necessary changes myself but I was wondering if this is maybe being worked on already?

**Comment by joaopsilva** [comment]
Hi @brintal , a PR for implementing these changes would be very much appreciated. Thanks.

**Comment by brintal** [comment]
@joaopsilva 
I've seen that most of the changes were already covered by other PRs. 
Nevertheless I created one for the small changes that I found are still missing:
https://github.com/binance-exchange/binance-java-api/pull/160

**Comment by joaopsilva** [comment]
Thanks @brintal , I've merged it.
