### ISSUE TITLE
Out of order user events

### ISSUE THREAD

**Issue by jkolobok** [binance-exchange/binance-java-api#162]
According to documentation out of order events may arrive during heavy load. 
https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md
and they are supposed to be sorted using even time. But API dosn't handle this. Also, it's not clear how large should be the buffer so that out of order event arrives with 99% probability.  
This API doesn't handle it

**Comment by joaopsilva** [comment]
The API merely fetches the data, it's up the client to order the events according to whatever logic is deemed necessary for the application.
