### ISSUE TITLE
Getting a ListenKey with my API key & Secret

### ISSUE THREAD

**Issue by Amarog** [binance-exchange/binance-java-api#168]
Hi, 

not sure if I'm in the right place. I've looked and looked and looked on google for day's now but I can't find anything on how I can get a ListenKey and use it in Javascript. 

All I can find are pre-build libraries. 

I'm pretty n00bish when it comes to Javascript. So far I've been able to pull all the live trades and the orderbook from the websocket. But that's public information. Now I want to connect to my own datastream. 

I use CCXT to get my balances and such and that works great. But I'm writing my own now and that does not support websockets yet. 

So, my questions is: How can I connect via Javascript to my own User Data stream? What code do I need to write to insert my Api key & Secret so I can get a ListenKey and use that to retrieve my live data? 

A good push in the right directions would be greatly appreciated. 
Thanks in advance dor any help!

**Comment by joaopsilva** [comment]
Hi @Amarog , please bear in mind that this is Java API, not a JavaScript one, which you can find at https://github.com/binance-exchange/node-binance-api. There are also some examples there on how to setup your application with your keys, written in JavaScript.
