### ISSUE TITLE
Failure to find com.binance.api in Maven repository 

### ISSUE THREAD

**Issue by wrone** [binance-exchange/binance-java-api#171]
Maven installed, dependency added

`<dependency>
	<groupId>com.binance.api</groupId>
	<artifactId>binance-api-client</artifactId>
	<version>1.0.0</version>
</dependency>`

**Error Message:**
Failed to execute goal on project binance-bot: Could not resolve dependencies for project org.binance.bot:binance-bot:jar:1.0.0-SNAPSHOT: Failure to find com.binance.api:binance-api-client:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]

**Comment by wrone** [comment]
i guess the correct "binance-api-client" is missing here https://mvnrepository.com/search?q=binance

**Comment by big-andy-coates** [comment]
The library is not currently available on maven central. See #3. 

Closing as a duplicate.
