### ISSUE TITLE
What to do after Maven build succeeded?

### ISSUE THREAD

**Issue by Zynatrixx** [binance-exchange/binance-java-api#172]
I'm using Eclipse and I' have a Maven project that includes the library (it is in Eclipse), the dependencies in the xml file and my own programm code.
After I added the Apikey and secretkey to the variables, I ran it as a Maven build (took "clean verify" as lifecycle, idk what thsi is, just random picked one...) succeeded, but now?
What do I have to do now for connecting to the API?
I'm very grateful for eyerone who can help me, I' pretty young and want to learn coding, also crypto interests me, so I want to combine it... Sry if this is a bonehead question :/

**Comment by joaopsilva** [comment]
Hi @Zynatrixx , to connect to the API you need to use either the REST client or the WebSocket client. The best way to get started is by running the examples in the example folder, and then start adapting that code for your specific needs.
