### ISSUE TITLE
24h statistics using webSocket?

### ISSUE THREAD

**Issue by greekphilip** [binance-exchange/binance-java-api#180]
Is there any way to get the 24Statistics using a websocket? I don't want to use Candlestick.Interval_DAILY because that returns the statistics from 3:00 a.m. I wan't the statistics of the last 24 hours as they are shown on the binance website.

**Comment by iluz0r** [comment]
`client.getAll24HrPriceStatistics();`

**Comment by joaopsilva** [comment]
No, you need to use the REST API (`client.getAll24HrPriceStatistics();`).
