### ISSUE TITLE
com.fasterxml.json.core.JsonParseException constantly and randomly thrown. 

### ISSUE THREAD

**Issue by antonvalletas** [binance-exchange/binance-java-api#186]
I have a trading bot using the REST API that when asking for market data, sometimes gets this exception: 

```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: okhttp3.ResponseBody$BomAwareReader@7699ccb9; line: 1, column: 2]
```

These are randomly thrown but constantly through out the day. Could be 5 times in 5 minutes, 10 times in 5 minutes, and then a few hours without any exceptions thrown, this is what is making it hard for me to figure this out. Any help appreciated.

**Comment by antonvalletas** [comment]
Something is making me think this has something to do with issue #10 , I will confirm later.

**Comment by antonvalletas** [comment]
For some reason this is related to API requests as I suspected, even though I am sure I am not surpassing the 1200 Requests (weighted) per minute, since I did that and the error was:

`Exception caught!! Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.
`

Instead of the one I am getting. However, turning the API requests per minute down to around 800 or 700, makes this error disapear.

Any help?

**Comment by antonvalletas** [comment]
Seems this error is produced by CloudFront. It seems that it randomly intercepts requests to the API and insted responds with a cloudfront page, which seems stupid while the 1200 weighted requests are met.

Binance Support refuses to tell me how to avoid this, while my app only polls about 800 times per minute (weighted) it still gets those cloudfront pages every few minutes or hourse. Just had to add a few try-catches to avoid this stupid error messing with my program, but it makes no sense to advertise 1200 weighted requests on the API while the firewall intercepts packets at waaaaaay less.

Lets hope this gets fixed at some point on Binance's side, and that the API is updated to manage it correctly.

**Comment by joaopsilva** [comment]
Closing this ticket, as at the moment, there is nothing that can be done from the API side to fix it.
