### ISSUE TITLE
[Solved] Binance Sandbox API

### ISSUE THREAD

**Issue by sadra** [binance-exchange/binance-java-api#188]
If you use [Node Binance Library](https://www.npmjs.com/package/node-binance-api) you can set your client to work on sandbox mode:

```js
const binance = require('node-binance-api')().options({
  APIKEY: '<key>',
  APISECRET: '<secret>',
  useServerTime: true, // If you get timestamp errors, synchronize to server time at startup
  test: true // If you want to use sandbox mode where orders are simulated
});
```
Is there any way to trade on sandbox mode with this `java` library?

**Comment by eugene-kamenev** [comment]
@sadra Use
https://github.com/binance-exchange/binance-java-api/blob/master/src/main/java/com/binance/api/client/BinanceApiRestClient.java#L172 
method to place orders

**Comment by sadra** [comment]
> @sadra Use
> https://github.com/binance-exchange/binance-java-api/blob/master/src/main/java/com/binance/api/client/BinanceApiRestClient.java#L172
> method to place orders
Thank you Dear @eugene-kamenev 
But can we check the order at any sandbox panel/API or it just makes a fake order inside the app?

**Comment by eugene-kamenev** [comment]
@sadra Check please: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#test-new-order-trade
