### ISSUE TITLE
Ping/Pong ERROR -> Out of memory

### ISSUE THREAD

**Issue by kustrun** [binance-exchange/binance-java-api#192]
While connected to WebSocket for some time it happens that Binance WebSocket for ticker/orderbook channel tries to receive pong from server which fails after 20 seconds. This happens after random time has passed. After that the program continuously tries to successfully receive pong from server and I assume that it fills up memory until the Java program is terminated with OutOfMemory error. 

Java version: 1.8
Binance WebSocket version: 7a1fc4f74f

In the attachment I include application log and Java memory dump.

[app.log](https://github.com/binance-exchange/binance-java-api/files/2625067/app.1.log)
[hs_err_pid6668.log](https://github.com/binance-exchange/binance-java-api/files/2625069/hs_err_pid6668.log)

**Comment by kustrun** [comment]
Today I received another similar problem with WebSocket connectivity. The program was running for some time and when I checked it I noticed that it stopped receiving data from WebSocket. When I tried to force close the program and then rerun it the program crashed with the following Java memory dump.  

[hs_err_pid7654.log](https://github.com/binance-exchange/binance-java-api/files/2640593/hs_err_pid7654.log)

Any help?

**Comment by joaopsilva** [comment]
Hi @kustrun , are you using the latest version of the API? Are you able to provide me with a succint test case that reproduces the problem?

**Comment by kustrun** [comment]
I was using the version from Sep 13, 2018. Do you believe the newest version from today would solve the problem?

**Comment by joaopsilva** [comment]
No, nothing particularly relevant was changed yesterday. Could you please provide me with a test that can reproduc the problem? Thanks.

**Comment by kustrun** [comment]
The problem is I am not able to reproduce it on localhost, but on production server the program randomly crashes.

**Comment by eugene-kamenev** [comment]
@kustrun Please check if this implementation solves the issue for you:
https://github.com/eugene-kamenev/binance-better-websocket

**Comment by iauglov** [comment]
+1 
2019-01-21 16:18:00.802 ERROR 5012 --- [ce.com:9443/...] i.n.m.binance.BinanceOrderBookCallback   : BOCBC

java.net.SocketTimeoutException: sent ping but didn't receive pong within 20000ms (after 0 successful ping/pongs)
	at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:545) [okhttp-3.10.0.jar:na]
	at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:529) [okhttp-3.10.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

Version: 1d0eef80cf from jitpack

**Comment by tomastoth** [comment]
> +1
> 2019-01-21 16:18:00.802 ERROR 5012 --- [ce.com:9443/...] i.n.m.binance.BinanceOrderBookCallback : BOCBC
> 
> java.net.SocketTimeoutException: sent ping but didn't receive pong within 20000ms (after 0 successful ping/pongs)
> at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:545) [okhttp-3.10.0.jar:na]
> at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:529) [okhttp-3.10.0.jar:na]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
> at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_181]
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_181]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
> at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
> 
> Version: [1d0eef8](https://github.com/binance-exchange/binance-java-api/commit/1d0eef80cfad1186a9e1bf0f3affeb2ad7175bbc) from jitpack

Same happening to me. Trying to fix

**Comment by joaopsilva** [comment]
Memory issues have been fixed, for the ping/pong problem, please continue the discussion in https://github.com/binance-exchange/binance-java-api/issues/202.
