### ISSUE TITLE
AllMarketTickersEvent

### ISSUE THREAD

**Issue by Gtofig** [binance-exchange/binance-java-api#197]
AllMarketTickersEvent does not contain bid price

Somehow AllMarketTickersEvent class does not contain bid price. Official docs indicate two bid related fields here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md
  "b": "0.0024",      // Best bid price
  "B": "10",          // Best bid quantity

But the AllMarketTickersEvent lacks these.

**Comment by joaopsilva** [comment]
Fixed #198
