### ISSUE TITLE
TradeFee

### ISSUE THREAD

**Issue by crosstec** [binance-exchange/binance-java-api#211]
Hi,
I added TradeFee retrieval, for some reason it is missing in the current version.

Is it worth trying to push this change into the main repo?

I mean, is somebody here that would pick it up and look at it for possible inclusion before I take the efforts to fork and do a pull request?

Thanks!

**Comment by joaopsilva** [comment]
Hi @crosstec , it is indeed, please go ahead and create the PR, I will merge it after reviewing. Thanks.

**Comment by oriamrm** [comment]
Hey guys, I am now using the latest version - I downloaded the repository and compiled it myself - and still, I can't get the TradeFee.

account.getTakerCommission() just returns 10, regardless of what my actual fees are (I have bought some BNB to change them and still it returns 10).

Or is that even what you guys were talking about?
Anyway, when is this going to be resolved?

**Comment by joaopsilva** [comment]
Hi @oriamrm , the values returned are based on your Trading Fee Level, which are 0.10% for both maker and taker fee. The 25% rebate you get from holding BNB does not change your level (VIP 0), and therefore they are not returned by the API, you will need to apply discount manually.

More details at https://www.binance.com/en/fee/schedule.
