### ISSUE TITLE
Timestamp for this request is outside of the recvWindow

### ISSUE THREAD

**Issue by spapapan** [binance-exchange/binance-java-api#212]
I am trying to make a request using this code:
```

public JsonObject account() throws BinanceApiException { 
        return (new Request(baseUrl + "v3/account"))
                .sign(apiKey, secretKey, null).read().asJsonObject();
    }
```

but I get this error:

> 
    BinanceApiException: ERROR: -1021, Timestamp for this request is outside of the recvWindow.

I know that it has something to do with the time synchronization between my computer and the server. I don't get this error every time I run this code. In the past I solved this error by going to Windows settings, Date and Time, Internet Time Settings and synchronize my time to time.windows.com.

How can I solve this ?

**Comment by oriamrm** [comment]
When any time synchronization error occurs with Binance's servers, I reset my datetime in this way:
1) Search "Date & Time Settings" In windows
2) Disable the "Set time automatically" button
3) Click "Change" and change the time (Yes, this is crucial)
4) Re-Enable the "Set time automatically" button
5) Wait a bit until windows synchronizes the time again

Et Voila!
I hope this will solve your problem.

**Comment by joaopsilva** [comment]
Indeed, this is a local issue, there is not much we can do at the API/client level.

**Comment by moemar** [comment]
> When any time synchronization error occurs with Binance's servers, I reset my datetime in this way:
> 
> 1. Search "Date & Time Settings" In windows
> 2. Disable the "Set time automatically" button
> 3. Click "Change" and change the time (Yes, this is crucial)
> 4. Re-Enable the "Set time automatically" button
> 5. Wait a bit until windows synchronizes the time again
> 
> Et Voila!
> I hope this will solve your problem.

This helped for me!

**Comment by yairelmaliah** [comment]
> When any time synchronization error occurs with Binance's servers, I reset my datetime in this way:
> 
> 1. Search "Date & Time Settings" In windows
> 2. Disable the "Set time automatically" button
> 3. Click "Change" and change the time (Yes, this is crucial)
> 4. Re-Enable the "Set time automatically" button
> 5. Wait a bit until windows synchronizes the time again
> 
> Et Voila!
> I hope this will solve your problem.

works for me either , thanks !
