### ISSUE TITLE
WebSocket auto stop sending data to client  after 30 miniutes

### ISSUE THREAD

**Issue by noodlespan** [binance-exchange/binance-java-api#218]
This is the codes

@Component
@Log4j2
public class BinanceApiWebSocketListener2 {
    @Autowired
    private BinanceApiWebSocketClient binanceApiWebSocketClient;
    @PostConstruct
    public void init() {
        //listener
        binanceApiWebSocketClient.onDepthEvent(Constant.btcusdt, (DepthEvent response) -> {
            System.out.println("buy:"+response.getBids().get(0).getPrice()+","+"sell:"+response.getAsks().get(0).getPrice());
        });
        System.out.println("Waiting for events...");
    }
}

**Comment by mcourteaux** [comment]
You need to ping it. See the official docs.

**Comment by mcourteaux** [comment]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/user-data-stream.md#pingkeep-alive-a-listenkey

**Comment by joaopsilva** [comment]
Indeed, what @mcourteaux said.
