### ISSUE TITLE
I can't download with gradle. How can it?

### ISSUE THREAD

**Issue by cinabro88** [binance-exchange/binance-java-api#23]
Can I this api with gradle?

**Comment by saketpotluri** [comment]
It is not in mavenCentral repository. What I did was clone the repository, `mvn install`, then add the generated jar into IntelliJ.

**Comment by joaopsilva** [comment]
Indeed, I will be adding this to mavenCentral hopefully this month, you can follow the issue at https://github.com/binance-exchange/binance-java-api/issues/3.
