### ISSUE TITLE
How to get all pairs and then get level 1 quote

### ISSUE THREAD

**Issue by jnovotny** [binance-exchange/binance-java-api#27]
Hi,

My apologies I could't find a forum to post this question to.

I want to get a list of all trading pairs on Binance and then for each of these pairs I'd like to subscribe to get 3 min candlestick data (really just latest quote price) 

Thanks, Jason

**Comment by joaopsilva** [comment]
Hi @jnovotny. For getting all the trading pairs, you can call the `getExchangeInfo` method. Then, for each of those pairs, you can call `getCandlestickBars(symbol, frequency)`.

**Comment by jnovotny** [comment]
Hi Joao,

Thanks for the help! I'm actually interested in probably using the 
websocket call to get candlestick data-- basically I want to receive 
latest (by 3 min) price for all of these pairs.

The thing is I can do something like:

client.onCandlestickEvent("ZECETH", CandlestickInterval.THREE_MINUTES, 
response -> System.out.println(response));

but how do I do this for all the pairs?

If I do this:

client.onCandlestickEvent("ZECETH", CandlestickInterval.THREE_MINUTES, 
response -> System.out.println(response)); 
client.onCandlestickEvent("BTCETH", CandlestickInterval.THREE_MINUTES, 
response -> System.out.println(response));

It won't actually get to the 2nd line-- or do I need to run each of 
these in its own thread or some other way? Thanks, Jason
