### ISSUE TITLE
Please help me with java api LOT_SIZE error

### ISSUE THREAD

**Issue by Grebyn35** [binance-exchange/binance-java-api#278]
Hi, im building an algo with this API however i keep getting the LOT_SIZE error, the cause is by making a market/limit order that the decimal precision value is incorrect. I know i can get the right precision with the .getStepSize function, or the getExchangeInfo() but its not working!!! I keep getting this error

"Cannot deserialize value of type `com.binance.api.client.domain.general.FilterType` from String "MAX_POSITION": value not one of declared Enum instance names: [MARKET_LOT_SIZE, ICEBERG_PARTS, EXCHANGE_MAX_NUM_ORDERS, MAX_ALGO_ORDERS, MAX_NUM_ORDERS, EXCHANGE_MAX_ALGO_ORDERS, MAX_NUM_ALGO_ORDERS, PRICE_FILTER, LOT_SIZE, MAX_NUM_ICEBERG_ORDERS, MIN_NOTIONAL, PERCENT_PRICE]"

I have tried to use the filter type with all of these options but its the same error. Please help me get the precision value for the quantity i have not slept for 2 days

**Comment by truonghatsts** [comment]
It was fixed in this https://github.com/binance-exchange/binance-java-api/pull/276

**Comment by Grebyn35** [comment]
Thanks, saved me ALOT of time.
