### ISSUE TITLE
Correct way to split trading symbols?

### ISSUE THREAD

**Issue by Blogshot** [binance-exchange/binance-java-api#31]
Hello,

in my App I want to calculate a Dollar-price for every coin by getting all trading pairs and matching them up.
Let's say I want to get the worth of IOTA in dollar. I get IOTA/ETH and continue to get ETH/USD. Now I can calculate IOTA/USD and display it.

The problem is this:
Calling getAllPrices() results in symbols like `ETHBTC`, `WAVESBTC` or `NEBLBTC`.

There is no indicator where to split the two coins. Since symbols can be different length, I can't just split them in the center. 

How can I split them correctly?

**Comment by joaopsilva** [comment]
Hi,

There are only 4 quote assets: `BTC`, `ETH`, `USDT`, and `BNB`, so you can use a regex to match the base asset, something like `(.*)(BTC|ETH|USDT|BNB)`, and extract it.

Otherwise, you can use the `getExchangeInfo` method, which for each symbol (e.g. IOTAETH), will give you the base asset (IOTA) and quote asset (ETH).

Hope it helps.

**Comment by learnathoner** [comment]
Using Regex in **Javascript**:
```
const baseCurrencies = /(\w+)((USDT)|(ETH)|(BTC)|(USDT))$/g;
const result = baseCurrencies.exec(symbol);
```
Running this on symbol `ETHUSDT`, result will be an array with ['ETHUSDT', 'ETH', 'USDT'].

**Comment by doctorx32** [comment]
According to https://support.binance.com/hc/en-us/articles/115000594711-Trading-Rule , it seems like there are added extra base currencies, such as `PAX`, `USDC`, `USDS`

**Comment by ace314** [comment]
Use pandas DataFrame can extract the quote assets:
`
info = client.get_exchange_info()
df_info = pd.DataFrame.from_dict(info['symbols'])
df_info['quoteAsset'].unique()
`

This would give:
`array(['BTC', 'ETH', 'USDT', 'BNB', 'TUSD', 'PAX', 'USDC', 'XRP', 'USDS',
       'TRX', 'BUSD', 'NGN', 'RUB', 'TRY', 'EUR', 'ZAR', 'BKRW', 'IDRT',
       'GBP', 'UAH', 'BIDR', 'AUD', 'DAI', 'BRL', 'BVND', 'VAI', 'USDP',
       'DOGE', 'UST', 'DOT', 'PLN', 'RON', 'ARS'], dtype=object)`
