### ISSUE TITLE
the minimal quantity interval?

### ISSUE THREAD

**Issue by LiYijin** [binance-exchange/binance-java-api#32]
The binance's trading rule  only gives the min Amount of every coin, not give the min amount interval. Do someone know the min amount interval of every coin or where can I find it? Thanks a lot!

For example, the min amount for ETH/BTC is 0.001ETH, what about its min interval? still 0.001?

**Comment by joaopsilva** [comment]
You can use the `getExchangeInfo` method. `getTickSize()` will return what you need.
