### ISSUE TITLE
getDepositAddress or getDepositHistory return null

### ISSUE THREAD

**Issue by klaszlo8207** [binance-exchange/binance-java-api#330]
**I am using this in android, gradle:**

`implementation "com.github.binance-exchange:binance-java-api:master-SNAPSHOT"`

**I created an API KEY in binance API management, and after I just want to getDepositAddress or getDepositHistory, but this is always success = false**

What is the probleme here? 

serverTime is ok

getDepositAddress DepositAddress[address=<null>,success=false,addressTag=<null>,asset=<null>]

DepositHistory[depositList=,success=false,msg=-1021=Timestamp for this request was 1000ms ahead of the server's time.]

**Comment by klaszlo8207** [comment]
DepositHistory[depositList=<null>,success=false,msg=-1021=Timestamp for this request was 1000ms ahead of the server's time.]

**Comment by MajidKeshtidar** [comment]
I have this problem too. If you can resolve it please help me

**Comment by klaszlo8207** [comment]
> 
> 
> I have this problem too. If you can resolve it please help me

1, You have to **download the source zip** and add to your project, **remove from dependencies**
2, in **BinanceApiRestClientImpl** you have to refactor all:

BinanceApiConstants.DEFAULT_RECEIVING_WINDOW,  **System.currentTimeMillis()**

to

BinanceApiConstants.DEFAULT_RECEIVING_WINDOW,  **getTimeStamp()**

where **getTimeStamp** is

    private long getTimeStamp() {
        long start = System.currentTimeMillis();
        long serverTime = this.getServerTime();
        long end = System.currentTimeMillis();
        long gap = end - start;
        return serverTime + gap;
    }
