### ISSUE TITLE
Filter failure: LOT_SIZE

### ISSUE THREAD

**Issue by Xamez** [binance-exchange/binance-java-api#331]
Good evening,
Here's my error, yet everything looks good?

![error](https://user-images.githubusercontent.com/35816109/110253510-0bcb8100-7f8b-11eb-871b-6726eee1517b.png)

If anyone has an idea?

**Comment by KillerInk** [comment]
with step size is meant how it get increased. 
valid would be 0.00000100 
but not 0.00000150
so next step must be 0.00000200 to be valid. 
your lot size is about 0.00000053 to big

**Comment by Xamez** [comment]
I don't really understand, am I trading with too much money or not enough? Because I trade with something like 0.03BTC. How do I fix my problem in this case? Do you have a discord or something to be able to communicate faster?

**Comment by KillerInk** [comment]
the screenshot show a lot size from 0.04749053
so its between 0.00000100 and 9000. this is so far correct.

but now the step size comes in wich require the lot need to be diffable through the step size.

0.047490**53** need to get to 0.047490**00**

**Comment by Xamez** [comment]
Oh yes, I see! Thank you very much, I'll try it out
