### ISSUE TITLE
Cannot close webSocketClient

### ISSUE THREAD

**Issue by DMan326159** [binance-exchange/binance-java-api#333]
If I want to stop the listener (say when a JavaFX button is pressed), how do I go about it? If I do as it is written:
```
Closable ws = client.onAggTradeEvent ("ethbtc", someCallback);
// some time later ...
ws.close ();
```
then I get:

` java.lang.NullPointerException: Parameter specified as non-null is null: method okhttp3.WebSocketListener.onClosed, parameter reason`

**Comment by LeoAlmDiniz** [comment]
How did you solve this?
