### ISSUE TITLE
Maven version numbering not following standards

### ISSUE THREAD

**Issue by chetmichals** [binance-exchange/binance-java-api#35]
The version number used for this project is set for a release version, but a number of code changes have been made under the same released version number.

Ideally a single commit should be considered the "released" version whenever you feel is apt, and all in between development versions should be labeled snapshot. The way it is now, it would not play nice with a Maven Repo. 

The change I would suggest it to make the version 1.0.1-SNAPSHOT, where the snapshot qualifier is used to indicate it is a development build. This version scheme works properly with the various Maven Repositories I have used.

If you want to read up a bit more on Maven's number scheme, you can see it here: 
https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8855

**Comment by joaopsilva** [comment]
Hi @chetmichals , thanks for your feeedback. You're right, and that is indeed the goal, once the library is on Maven Central (issue being discussed at https://github.com/binance-exchange/binance-java-api/issues/3).
