### ISSUE TITLE
UserDataUpdateEvent: ACCOUNT_UPDATE is wrong

### ISSUE THREAD

**Issue by mcourteaux** [binance-exchange/binance-java-api#355]
The issue is this enum definition:
https://github.com/binance-exchange/binance-java-api/blob/7781ee05492b197a6c6b54ac0dd0684e194e536e/src/main/java/com/binance/api/client/domain/event/UserDataUpdateEvent.java#L91

 - The Binance documentation says this doesn't exist: https://github.com/binance/binance-spot-api-docs/blob/master/user-data-stream.md#web-socket-payloads
 - There is only: `outboundAccountPosition`, `balanceUpdate`, `executionReport`, `listStatus`.
 - People have struggled with this (including me): https://github.com/binance-exchange/binance-java-api/issues/309

**Comment by PanderBoy18** [comment]
I have the same problem. I changed my code in the updateEvent to:
```
if (newEvent.getEventType() ==
    UserDataUpdateEvent.UserDataUpdateEventType.ACCOUNT_UPDATE) {
    System.out.println("### ACCOUNT_UPDATE");
    AccountUpdateEvent accountUpdateEvent = newEvent.getAccountUpdateEvent();
    // Print new balances of every available asset
    System.out.println(accountUpdateEvent.getBalances());
} else if (newEvent.getEventType() ==
           UserDataUpdateEvent.UserDataUpdateEventType.ORDER_TRADE_UPDATE) {
    System.out.println("### ORDER_TRADE_UPDATE");
    System.out.println(newEvent.getOrderTradeUpdateEvent().toString());
} else if (newEvent.getEventType() ==
           UserDataUpdateEvent.UserDataUpdateEventType
               .ACCOUNT_POSITION_UPDATE) {
    System.out.println("### ACCOUNT_POSITION_UPDATE");
    System.out.println(newEvent.toString());
} else if (newEvent.getEventType() ==
           UserDataUpdateEvent.UserDataUpdateEventType.BALANCE_UPDATE) {
    System.out.println("### BALANCE_UPDATE");
    System.out.println(newEvent.toString());
} else {
    System.out.println("### Unknown user account event type");
    System.out.println(newEvent.toString());
}
```

But I still have the same problem. What code do I need to change to get this working or is this issue not fixed yet?
