### ISSUE TITLE
DEAD PROJECT! lets find next alternative

### ISSUE THREAD

**Issue by mohamnag** [binance-exchange/binance-java-api#365]
looking at the long list of PRs and issues here leads only to one conclusion: this project is dead and we need an alternative. Lets find one so that we concentrate and improve instead of trying to recover the dead.

I found in the comments one alternative which looks pretty recent:
- https://github.com/mah454/binance-java-api by @mah454

please add any more up-to-date one here as a comment and lets find one that works properly and move on!

**Comment by icemagno** [comment]
Indeed. Thanks.

**Comment by mohamnag** [comment]
this one also looks promising: https://github.com/KillerInk/binance-java-api by @KillerInk

**Comment by klaszlo8207** [comment]
> this one also looks promising: https://github.com/KillerInk/binance-java-api by @KillerInk

Does this support OCO order?

I need something like this:

1, add a limit buy order task to <=0.57 usdt
2, listening on that order
3, if that order is executed and ended then I need an OCO sell order with values:
>=0.67
0.55
0.549

Can your fork do this job for me?

**Comment by KillerInk** [comment]
i merged the future changes from mah454 and added liquidswap, saving etc history.
currently oco is not supported but there is a pull request that seems to work.
my fork gets extended with my needs. 
but at current state i only need the historys from all endpoints for my assettracker.

**Comment by klaszlo8207** [comment]
> i merged the future changes from mah454 and added liquidswap, saving etc history.
> currently oco is not supported but there is a pull request that seems to work.
> my fork gets extended with my needs.
> but at current state i only need the historys from all endpoints for my assettracker.

Can u merge the OCO codes?

**Comment by mohamnag** [comment]
@KillerInk maybe a good start is for you to open the issues on your project so that we could move there. also another step would be to get the artifact versioned and published to central. but these could then be done on your repo maybe.

**Comment by klaszlo8207** [comment]
> @KillerInk maybe a good start is for you to open the issues on your project so that we could move there. also another step would be to get the artifact versioned and published to central. but these could then be done on your repo maybe.

Alsi I coundn't find the issues list on that fork

**Comment by klaszlo8207** [comment]
> @KillerInk maybe a good start is for you to open the issues on your project so that we could move there. also another step would be to get the artifact versioned and published to central. but these could then be done on your repo maybe.

+1

**Comment by KillerInk** [comment]
lol no one ask me if i want to maintain it, its expected^^
my repo is also for android! also i have no plans to release packages.
what i can do is to put everything together and merge pull request. but i dont want to be the main dev that have to fixup everything asap.

**Comment by mohamnag** [comment]
@KillerInk actually lets hope that all those people who submitted a PR here will do the same over there. Its still a lot of work to manage them but it will hopefully be less that maintaining it alone even for your own use cases.

maybe you can make it clear in a kind of statement on readme that its a best effort and as is ;)

**Comment by mohamnag** [comment]
So at the end I decided to fork and improve the repo from what @KillerInk had. There were some problems that prevented me to use that one as it was for example using android specific classes and co. Its published to sonatype too: https://github.com/mohamnag/binance-client-java

**Comment by klaszlo8207** [comment]
> So at the end I decided to fork and improve the repo from what @KillerInk had. There were some problems that prevented me to use that one as it was for example using android specific classes and co. Its published to sonatype too: https://github.com/mohamnag/binance-client-java

Thanks, I will give it a try

**Comment by adkr** [comment]
Hey guys... Two things...
1. How do you deal with REST limits? As I can see currently all headers are ignored on okHttp client level and only mapped body to type is returned. Binance send in headers info about utilized limits. I started custom limiter implementation but its wrong way. I was thinking to fork somewhere and add a wrapper type which would keep rawResponse and mapped type till the place where response is returned from library so you can do whatever you want with it.
2. Would you be willing to try to work together on one, picked repo? That way we would avoid many repos, each with different changes/improvements.

Waiting for your thoughts,
Cheers!

**Comment by adkr** [comment]
@joaopsilva Why did u close that issue?
