### ISSUE TITLE
BinanceApiException on getCandlestickBars

### ISSUE THREAD

**Issue by klaszlo8207** [binance-exchange/binance-java-api#37]
val candlestickBars = client.getCandlestickBars(symbol.toUpperCase(), interval)

https://github.com/binance-exchange/binance-java-api/blob/master/src/test/java/com/binance/api/examples/CandlesticksCacheExample.java

I just wanted to test this code on my android device. but got this exception

com.binance.api.client.exception.BinanceApiException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.lang.Long from String value ("0.09763700"): not a valid Long value
                                                                        at [Source: okhttp3.ResponseBody$BomAwareReader@ee6ad3c; line: 1, column: 17] (through reference chain: java.util.ArrayList[0]->com.binance.api.client.domain.market.Candlestick["closeTime"])

**Comment by klaszlo8207** [comment]
it looks like the 

getCandlestickBars not working at all

but

onCandlestickEvent

working!

**Comment by Sduniii** [comment]
try following code and symbols need to be lowercase in this scenario:

`import com.binance.api.client.BinanceApiCallback;
import com.binance.api.client.BinanceApiWebSocketClient;
import com.binance.api.client.constant.BinanceApiConstants;
import com.binance.api.client.domain.event.AggTradeEvent;
import com.binance.api.client.domain.event.CandlestickEvent;
import com.binance.api.client.domain.event.DepthEvent;
import com.binance.api.client.domain.event.UserDataUpdateEvent;
import com.binance.api.client.domain.market.CandlestickInterval;
import com.binance.api.client.impl.BinanceApiWebSocketListener;
import gui.apis.Exchange;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.WebSocket;

import java.io.Closeable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class BinanceWebsocket implements BinanceApiWebSocketClient, Closeable {

    private OkHttpClient client;
    private List<WebSocket> webSockets;

    public BinanceWebsocket() {
        this.client = new OkHttpClient();
        this.webSockets = new ArrayList<>();
    }

    public void onDepthEvent(String symbol, BinanceApiCallback<DepthEvent> callback) {
        final String channel = String.format("%s@depth", symbol.toLowerCase());
        createNewWebSocket(channel, new BinanceApiWebSocketListener<>(callback, DepthEvent.class));
    }

    @Override
    public void onCandlestickEvent(String symbol, CandlestickInterval interval, BinanceApiCallback<CandlestickEvent> callback) {
        final String channel = String.format("%s@kline_%s", symbol.toLowerCase(), interval.getIntervalId());
        createNewWebSocket(channel, new BinanceApiWebSocketListener<>(callback, CandlestickEvent.class));
    }

    public void onAggTradeEvent(String symbol, BinanceApiCallback<AggTradeEvent> callback) {
        final String channel = String.format("%s@aggTrade", symbol.toLowerCase());
        createNewWebSocket(channel, new BinanceApiWebSocketListener<>(callback, AggTradeEvent.class));
    }

    public void onUserDataUpdateEvent(String listenKey, BinanceApiCallback<UserDataUpdateEvent> callback) {
        createNewWebSocket(listenKey.toLowerCase(), new BinanceApiWebSocketListener<>(callback, UserDataUpdateEvent.class));
    }

    private void createNewWebSocket(String channel, BinanceApiWebSocketListener<?> listener) {
        String streamingUrl = String.format("%s/%s", BinanceApiConstants.WS_API_BASE_URL, channel.toLowerCase());
        Request request = new Request.Builder().url(streamingUrl).build();
        this.webSockets.add(client.newWebSocket(request, listener));
    }

    public void closeWebSocket(String channel) {
        List<WebSocket> toDelete = new ArrayList<>();
        this.webSockets.forEach(webSocket -> {
            if (webSocket.request().url().toString().contains(channel.toLowerCase())) {
                webSocket.cancel();
                //webSocket.close(1000, "");
                toDelete.add(webSocket);
            }
        });

        this.webSockets.removeAll(toDelete);
    }

    @Override
    public void close() {
        client.dispatcher().executorService().shutdown();
    }
}`

**Comment by joaopsilva** [comment]
Hi @klaszlo8207 , I just did a quick test, and it seems to be working. Please let me know if this happens again, and for which trading pair.

**Comment by estebanweb** [comment]
Hi @joaopsilva,  I am facing the exact same issue.

**Comment by freezerdragon** [comment]
How can I import this library to my andorid project?

**Comment by xXSkyWalkerXx1** [comment]
The issue still exists.
