### ISSUE TITLE
Websocket - EOFException

### ISSUE THREAD

**Issue by bavodaniels** [binance-exchange/binance-java-api#373]
I'm have the following code

`wsClient.onAllBookTickersEvent(new BinanceApiCallback<BookTickerEvent>() {
            @Override
            public void onResponse(BookTickerEvent bookTickerEvent) {
                System.out.println(bookTickerEvent.getSymbol());
            }

            @Override
            public void onFailure(Throwable cause) {
                System.out.println("Websocket error, " + cause);

            }
        });`

and after a while i get a EOFException (read somewhere around 1 minute)
any idea what this could be?

**Comment by cheeringsoul** [comment]
i have the same question, how did you solved it ?
