### ISSUE TITLE
ETH/USD chart

### ISSUE THREAD

**Issue by klaszlo8207** [binance-exchange/binance-java-api#38]
I want to draw a chart from the last (24H or 1 week) lets say ethereum values
How can I do this with binance API?

**Comment by joaopsilva** [comment]
You can use a library such as JFreeChart: http://www.java2s.com/Code/Java/Chart/JFreeChartCandlestickDemo.htm

**Comment by klaszlo8207** [comment]
com.binance.api.client.exception.BinanceApiException: Invalid symbol.

:(

**Comment by joaopsilva** [comment]
Try `ETHUSDT`.

**Comment by klaszlo8207** [comment]
Tried with that:

com.binance.api.client.exception.BinanceApiException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of java.lang.Long from String value ("301.13000000"): not a valid Long value

**Comment by klaszlo8207** [comment]
I think they updated the API, right? And that is why we got all this exceptions from **getCandlestickBars**

Other toughts: I think they not give me the ETH-USD price, or ETH-EUR only the ETH-BTC ot XVG-ETH, etc..

So this is sad.. Am I right?

**Comment by joaopsilva** [comment]
Most likely yes, I'll have a look later. Or you can submit a pull request with the fix? Probably the field name or the order has changed.

**Comment by joaopsilva** [comment]
You can check the available pairs at https://www.binance.com/api/v1/exchangeInfo, or in Binance directly.

**Comment by klaszlo8207** [comment]
Thanks. I think USDT is an asset, I wanted USD only:) USD dollars (or euro) from ETH. I think there is no simple way for do that, so I have to calculate bymyself.

**Comment by joaopsilva** [comment]
Inded, you would have to calculate that yourself, by getting the USDT value of the quote asset.

**Comment by klaszlo8207** [comment]
Thanks @joaopsilva one more :)
```
        socket.onCandlestickEvent(symbol, interval) { response ->
            callback?.ok(response)
        }
```
I call this with **"xlmeth", CandlestickInterval.WEEKLY**

but this is called in 1 to X seconds again and again, and give me one line only.. I need the history only for the XMLETH
I think this is a realtime data right? How can I call the history of an assset price? So I need to download the last 7 days prices, or just the 24 hours in one... Is it possible?
