### ISSUE TITLE
Updated JAR file

### ISSUE THREAD

**Issue by Charles26** [binance-exchange/binance-java-api#385]
Hi, is it possible to get an updated .jar of your API? 
I've been looking for it everywhere but couldn't find it.
Thanks a lot!

**Comment by Serg-Maximchuk** [comment]
> Hi, is it possible to get an updated .jar of your API?
> I've been looking for it everywhere but couldn't find it.
> Thanks a lot!

Hi, I have fixed this and published [my fork](https://github.com/Serg-Maximchuk/binance-java-api) to the [maven central](https://mvnrepository.com/artifact/io.github.serg-maximchuk/binance-api-client), new version is 1.0.3

**Comment by Charles26** [comment]
Thanks Serg-Maximchuk for your fast reply. I've checked and version 1.0.3 is not available yet. It's only showing: 1.0.1 and 1.0.2 versions.
