### ISSUE TITLE
Is there a way to calculate the candlestick data like client.getCandlestickBars(symbol.toUpperCase(), "1sec") or even 0,1sec?

### ISSUE THREAD

**Issue by fromjgor** [binance-exchange/binance-java-api#39]
Hello @joaopsilva , experts.

I am looking for an approach to calculate the candlesticks for an interval less than 1sec which is not supported by binance API.

I don't know: maybe it is possible by mixing of agg trades and order book data that available from API?

Thanks a lot!

**Comment by klaszlo8207** [comment]
Why do you need that?

**Comment by joaopsilva** [comment]
Hi, not really, no.

**Comment by fromjgor** [comment]
Thanks @joaopsilva! 

@klaszlo8207: It was about using this framework for a HFT.

**Comment by klaszlo8207** [comment]
What is HFT?

**Comment by xezon** [comment]
Both, aggtrade events give you access to the last bid and ask prices. So yes you can build your own candles for any time frame based on the bid/ask.

**Comment by joaopsilva** [comment]
That's true, you can't get that info from the candlestick API, but you could derive it from the aggtrades. /cc @klaszlo8207

**Comment by fromjgor** [comment]
Hi everybody.
thank you very much! 
Having tried to implement some examples I also found out that Web Sockets API is not stable enough without error handling properly implemented.

@joaopsilva it would be really great to provide such functionality which @xezon was also asking for.

Regards, fromjgor

@klaszlo8207 HFT was for high frequency trading

**Comment by zagorulkinde** [comment]
@fromjgor Have you tried to implement such thing using current api? Could you share example?
