### ISSUE TITLE
User data stream premature closing

### ISSUE THREAD

**Issue by octn** [binance-exchange/binance-java-api#4]
Hi, I am using the provided example (UserDtaStremExample) to listen to order statuses for a specific user. But when I open a user data stream I can only get order statuses for a few minutes, then it stops reporting orders. According to binance documentation the user data stream should remain open for 60 minutes unless a keep alive message is sent. I experimented sending keep alive requests every 2 minutes but I still get the same problem.

**Comment by octn** [comment]
Hi, I am still having the same issue. Can anyone try and see whether it's working or not? I can get order update events for about 1-2 minutes than it goes silent.

```
public static void main(String[] args) 
{
	BinanceApiClientFactory factory = BinanceApiClientFactory.newInstance(key, secret);
	BinanceApiRestClient client = factory.newRestClient();
	String listenKey = client.startUserDataStream();
	BinanceApiWebSocketClient webSocketClient = factory.newWebSocketClient();

	webSocketClient.onUserDataUpdateEvent(listenKey, response ->
	{
		if (response.getEventType() == UserDataUpdateEventType.ACCOUNT_UPDATE)
		{
			AccountUpdateEvent accountUpdateEvent = response.getAccountUpdateEvent();
			System.out.println(accountUpdateEvent.getBalances());
		}
		else
		{
			OrderTradeUpdateEvent orderTradeUpdateEvent = response.getOrderTradeUpdateEvent();
			// Print details about an order/trade
			System.out.println(orderTradeUpdateEvent);
		}
	});
	System.out.println("Waiting for events...");
}
```

**Comment by alicanalbayrak** [comment]
I have the same problem, did you find any solution to this ?

**Comment by joaopsilva** [comment]
Fixed in https://github.com/binance-exchange/binance-java-api/commit/71556ef3073ad5586ef40479e18456ef394ea78e
