### ISSUE TITLE
account.balances not refreshing?

### ISSUE THREAD

**Issue by klaszlo8207** [binance-exchange/binance-java-api#40]
I made a buy on the binance web site

and I have a timer that is call

```
account.balances.forEach { balance ->
            if (balance.free != "0.00000000") {
            ...
            }
        }
```

but this is not refreshing, how can I refresh my account and balances after a buy?

**Comment by joaopsilva** [comment]
You need to fetch a new accounts object, by fetching it through the `getAccount` method. Otherwise, you can listen for changes in the account through the `BinanceApiWebSocketClient#onUserDataUpdateEvent`. An event is triggered whenever your account balance changes for any asset.
