### ISSUE TITLE
Filter failure LOT_SIZE

### ISSUE THREAD

**Issue by klaszlo8207** [binance-exchange/binance-java-api#44]
I have 0.93 xlm. I want to sell it with xlmeth.

I tried sell market with quantity 0.9 but give me Filter failure LOT_SIZE

**Comment by joaopsilva** [comment]
Hi @klaszlo8207, the minQty is 1. You can find these numbers by calling the `getExchangeInfo` method. It will return you the details about a trading pair, e.g. for XLMBTC:

`
{"filterType":"LOT_SIZE","minQty":"1.00000000","maxQty":"90000000.00000000","stepSize":"1.00000000"}
`

**Comment by soumala-github** [comment]
Hello Everyone, I m trying to buy, but I have exception like 

com.binance.api.client.exception.BinanceApiException: Filter failure: MIN_NOTIONAL
com.binance.api.client.exception.BinanceApiException: Filter failure: LOT_SIZE

ExchangeInfo exchangeInfo = client.getExchangeInfo();

                                            Optional<SymbolInfo> optionalMin = exchangeInfo.getSymbols().stream().filter(symbolInfo -> symbolInfo.getSymbol().equals(symbol)).findAny();
                                            
                                            float minOrder = 0f;
                                            float minQty = 0f;
                                            if (optionalMin.isPresent()) {
                                                minOrder = Float.parseFloat(optionalMin.get().getFilters().get(3).getMinNotional());
                                                minQty = Float.parseFloat(optionalMin.get().getFilters().get(2).getMinQty());
                                            }
                                            
                                            float quantity = (minOrder / closePrice[i]) ;
                                            quantity = (float) Utils.round(quantity, 2);

                                            if (quantity < minQty){
                                                quantity = (float) Utils.round(minQty, 2);
                                            }
