### ISSUE TITLE
Install library into your Maven's local repository by running mvn install

### ISSUE THREAD

**Issue by kkalugerov** [binance-exchange/binance-java-api#45]
Excuse me but which library exactly should be installed ? Thanks !

**Comment by kkalugerov** [comment]
I managed to do it myself.

**Comment by krypto-vaio** [comment]
Can you suggest how you resolved it ? @kkalugerov

**Comment by krypto-vaio** [comment]
Never mind. I figured that too :)

**Comment by kkalugerov** [comment]
Yes , you have to download the repository first with git clone... and then
install it as maven repository in your local repository.I have used this
example https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html
