### ISSUE TITLE
Can not change user because httpclient is in static field

### ISSUE THREAD

**Issue by klaszlo8207** [binance-exchange/binance-java-api#46]
I have two users with api key and secret, I couldn't change the user because of this line:

**BinanceApiServiceGenerator.java**

**private static OkHttpClient.Builder httpClient = new OkHttpClient.Builder();**

I changed this to:

```
    public static <S> S createService(Class<S> serviceClass, String apiKey, String secret) {
        OkHttpClient.Builder httpClient = new OkHttpClient.Builder();
```

And now it is working!

**Comment by joaopsilva** [comment]
I wouldn't recommend changing the internals of `BinanceApiServiceGenerator.java`, since this might change in the future. I would recommend spawning two JVMs, one for each user.

**Comment by klaszlo8207** [comment]
Can you help me how to do this? Any example? Thanks

**Comment by joaopsilva** [comment]
Hi @klaszlo8207 , just create two applications, and then launch them in parallel.

**Comment by klaszlo8207** [comment]
Any other ways?:) I need one app only with 2 users.

**Comment by joaopsilva** [comment]
No, you would have to implement the change you mentioned on your first post, but this might break in the future.
