### ISSUE TITLE
Exception in thread "main" com.binance.api.client.exception.BinanceApiException: Filter failure: LOT_SIZE

### ISSUE THREAD

**Issue by bigcong** [binance-exchange/binance-java-api#5]
我在LTCBTC市场当中，调用limitSell方法的时候，当quantity=0.943752像这个数字，就会报上面的错误（Filter failure: LOT_SIZE），但是我如果将quantity=0.2的这样的数字，就可以。那么的问题来了，我如何才能获取LTCBTC的配置呢，例如最小数量位数，最小数量，最小金额，最小金额位数呢？

**Comment by joaopsilva** [comment]
Hi, you can find the configuration for each symbol https://www.binance.com/api/v1/exchangeInfo. I will add this endpoint to the API soon.

**Comment by joaopsilva** [comment]
I've added support for the `exchangeInfo` endpoint, and you can now query lot size information through the API, please refer to the the `GeneralEndpointsExample` class.
