### ISSUE TITLE
BinanceApiCallback must have an onFailure() method

### ISSUE THREAD

**Issue by ab-taktik** [binance-exchange/binance-java-api#58]
The BinanceApiAsyncRestClient is useless if the caller of the async method isn't notified in case of error. 

The BinanceApiCallback interface must have an onFailure() method so that the caller can be notified of errors.

**Comment by joaopsilva** [comment]
Hi @ab-taktik, there's a pull request in https://github.com/binance-exchange/binance-java-api/pull/49, which exposes the `onFailure` method, I will be reviewing it this week and merging it to master. Stay tuned.

**Comment by fromjgor** [comment]
Hi @joaopsilvto , great! will be there some example like a cookbook how to implement the error handling properly? Maybe you could also recap the last changes (e.g. related to your recommendation to use singletons instead of creating API instance).
Thanks, @fromjgor

**Comment by joaopsilva** [comment]
Hi @ab-taktik , this is now implemented, please update your repository.

**Comment by ab-taktik** [comment]
@joaopsilva Thank you for the feedback! I'll update
