### ISSUE TITLE
getDepositAddress 

### ISSUE THREAD

**Issue by DizmalXC** [binance-exchange/binance-java-api#6]
When using the getDepositAddress function, I get "api not exist".  Does Binance support this function?

**Comment by joaopsilva** [comment]
Yes, the examples in the AccountEndpointsExample class are working. Could you provide me with the full stacktrace of the error? Also, in your API Setting, is the "Read Info" option checked?

**Comment by DizmalXC** [comment]
After comparing your test class with my code, I figured out that it wasn't your code.  I created a new API key and it worked.  I think the API settings for updating permissions may be delayed or have an issue.

Appreciate the help!

**Comment by joaopsilva** [comment]
Great to hear that!
