### ISSUE TITLE
How to shut down non-daemon threads?

### ISSUE THREAD

**Issue by cowwoc** [binance-exchange/binance-java-api#7]
If I run:

```
BinanceApiClientFactory factory = BinanceApiClientFactory.newInstance(API_KEY, API_SECRET);
BinanceApiRestClient client = factory.newRestClient();
TickerStatistics price = client.get24HrPriceStatistics("BTCUSDT");
System.out.println("Price: " + price.getLastPrice());
```

The JVM never shuts down. How do I shut down the non-daemon threads?

**Comment by cowwoc** [comment]
Correction: the JVM shuts down about a minute later, but I'd like to shut it down sooner (explicitly). Is there a method for that?

**Comment by joaopsilva** [comment]
Is that the only code you're running? It should shut down by itself immediately after the call. Otherwise, you can always call `System.exit(0)` to force the termination o the JVM.

**Comment by cowwoc** [comment]
It **should** shut down by itself immediately, but does not. Did you try reproducing this on your end?

I don't consider `System.exit()` an option because the idea is to shut down once all threads become idle. Today I've got a very simple program, but tomorrow I might want to wait for other threads (other than this API) to shut down and I won't know when it's safe to invoke `System.exit()`.

**Comment by joaopsilva** [comment]
Hi @cowwoc , I tried to reproduce the issue but I was unable to. From which context are you running the code above? A regular `main` entrypoint? Which version of Java are you using?

**Comment by cowwoc** [comment]
@joaopsilva Correct, my entire class file is as follows:

```
public final class Test
{
	private static final String API_KEY = "value-goes-here";
	private static final String API_SECRET = "value-goes-here";

	public static void main(String[] args) throws IOException
	{
		BinanceApiClientFactory factory = BinanceApiClientFactory.newInstance(API_KEY, API_SECRET);
		BinanceApiRestClient client = factory.newRestClient();
		TickerStatistics price = client.get24HrPriceStatistics("BTCUSDT");
		System.out.println("Price: " + price.getLastPrice());
        }
}
```

I see `Price` printing out, then the console sits there for another minute or so. Then it eventually quits. This is running against the master branch of this repository.

**Comment by VjekoslavKrainovic** [comment]
What is fix? I also have same problem.
