### ISSUE TITLE
is it possible to listen raw trade updates?

### ISSUE THREAD

**Issue by zagorulkinde** [binance-exchange/binance-java-api#70]
Hello. Is't possible to get raw trades stream using this library? I know that it's possible to get aggregated trade updates, but i could not find any information about raw trades.

https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md

**Comment by fromjgor** [comment]
Hello, a similar issue was discussed [here](https://github.com/binance-exchange/binance-java-api/issues/39)

**Comment by joaopsilva** [comment]
Duplicate of #39.
