### ISSUE TITLE
feature request :  get all trades from given orderid

### ISSUE THREAD

**Issue by krushnakant** [binance-exchange/binance-java-api#73]
like i pass order-id as parameter and get all Trades that are executed under this order.
currently   `GET /api/v3/myTrades  (HMAC SHA256)` not supporting this feature.

**Comment by joaopsilva** [comment]
Hi @krushnakant , unfortunately, the internal Binance API does not support this, so I can't support it in this client either. Please raise an issue in the official-api-docs project.
