### ISSUE TITLE
How to properly close Websocket

### ISSUE THREAD

**Issue by l16h7n1n6s** [binance-exchange/binance-java-api#76]
I am struggling to close the WebSocket. Does anyone know the right way to close it with all the available open threads.

```
[BinanceApiClientFactory factory = BinanceApiClientFactory.newInstance();
    BinanceApiWebSocketClient client = factory.newWebSocketClient();
    client.onDepthEvent(symbol.toLowerCase(), response -> {
      if (response.getUpdateId() > lastUpdateId) {
        System.out.println(response);
        lastUpdateId = response.getUpdateId();
        updateOrderBook(getAsks(), response.getAsks());
        updateOrderBook(getBids(), response.getBids());
        printDepthCache();
      }
    });
}](url)
```

there is no any `client.close()` i will appreciate if anybody may help me

**Comment by joaopsilva** [comment]
Hi @l16h7n1n6s , please see https://github.com/binance-exchange/binance-java-api#closing-web-sockets and update your repository with the latest changes.

**Comment by xrpking** [comment]
If I have multiple sessions open, eg. LTCBTC & ETHBTC and I want to keep one open and close the other. Is this possible? Do I close the whole stream then reopen with just one eg. ETHBTC?
