### ISSUE TITLE
Stop loss error

### ISSUE THREAD

**Issue by Pokit** [binance-exchange/binance-java-api#77]
Tried to place a stop loss limit order as so:
` NewOrder order = new NewOrder(symbolPairing, OrderSide.SELL, OrderType.STOP_LOSS_LIMIT, TimeInForce.GTC, trimAmountToBuy(accountBalanceCache.getAccountBalanceCache().get(tickerDump).getLocked()), sellPrice);`

` client.newOrder(order.stopPrice(stopLossPrice));`

Before this is done a limit sell is placed for a sell order at 5% higher than buy in price. The stop loss limit is placed at 5% lower than buy in price. The error I get from the stop loss limit sell is:
`Account has insufficient balance for requested action.`

The error is brought on by the limit sell being done before the stop loss, I was under the assumption you can have a stop loss and limit sell alongside each other? Without the limit sell it works perfectly, obviously quantity is changed to getFree() rather than getLocked().

Am I wrong in assuming you can't do a limit sell and a stop loss limit at the same time? If so, what solution would I go about doing?

**Comment by joaopsilva** [comment]
Hi @Pokit , indeed, currently, the amount always gets locked with all order types. Please try to reach out in the api's tg channel, and check if there's any alternative. If there is, I would be happy to support it in this API.

**Comment by bonobo1984** [comment]
Is anyone able to comment on the resolving change or solution to this particular issue?  Thanks
