### ISSUE TITLE
Desync, Timestamp for this request was 1000ms ahead of the server's time

### ISSUE THREAD

**Issue by Ptitlaby** [binance-exchange/binance-java-api#8]
Java version :
C:\Program Files\Java\jdk1.8.0_152\bin>java.exe -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

Quite a common error, here is the snippet of code I am using to compare the time between my computer and binance API :

```java
package laby.java;

import com.binance.api.client.BinanceApiClientFactory;
import com.binance.api.client.BinanceApiRestClient;

public class Main {

    private static final String APIKEY = "key";
    private static final String APISECRET = "secret";

    public static void main(String[] args) {

        BinanceApiClientFactory factory = BinanceApiClientFactory.newInstance(APIKEY, APISECRET);
        BinanceApiRestClient client = factory.newRestClient();


        while (true) {
            // Checking time between
            Long clientTime = java.lang.System.currentTimeMillis();
            Long serverTimerTime = client.getServerTime();
            System.out.println("Times : client[" + clientTime + "] server[" + serverTimerTime + "] diff[" + (serverTimerTime - clientTime) + "]");
        }
    }

}
```

Results:
```
Times : client[1514132675503] server[1514132675624] diff[121]
Times : client[1514132677246] server[1514132676946] diff[-300]
Times : client[1514132678541] server[1514132677226] diff[-1315]
Times : client[1514132678820] server[1514132677505] diff[-1315]
Times : client[1514132679098] server[1514132677788] diff[-1310]
Times : client[1514132679420] server[1514132678111] diff[-1309]
Times : client[1514132679729] server[1514132678414] diff[-1315]
Times : client[1514132680007] server[1514132678698] diff[-1309]
Times : client[1514132680293] server[1514132678983] diff[-1310]
Times : client[1514132680579] server[1514132679265] diff[-1314]
Times : client[1514132680858] server[1514132679544] diff[-1314]
Times : client[1514132681137] server[1514132679823] diff[-1314]
Times : client[1514132681417] server[1514132680107] diff[-1310]

Process finished with exit code 1
```

Registry setting is set to update time each ten minutes, it doesn't change anything:

![image](https://user-images.githubusercontent.com/5570178/34327874-25bfe84e-e8d0-11e7-99c2-13bffc10681e.png)

For your information, I updated the clock time before each attempt :
![image](https://user-images.githubusercontent.com/5570178/34327858-f691b232-e8cf-11e7-8ab4-e35f822d8814.png)

I am loosing around 1.2 seconds somewhere, and I don't know where

**Comment by JamesBarnes88** [comment]
I put a PR up for this #11. Its been working for a couple days so I think its safe. Not sure if its the best implementation though. Check it out if you want.

**Comment by joaopsilva** [comment]
@JamesBarnes88 many thanks for your PR, I'll review it in the upcoming days. The idea looks good, and it does solve the "problem", although I'm afraid it also hides away the fact that the client time is not ntp synchronised, as it should. This can have some consequences when reading out times returned by the API.

**Comment by Ptitlaby** [comment]
The thing is, even after manually synchronizing with a NTP server, the error is still there. And it's always around 1200 ms :<

**Comment by JamesBarnes88** [comment]
@joaopsilva Hey thanks for some clarification around the problem. Didn't know about NTP and SNTP before this. My question is if we use an NTPClient or SNTPClient implementation should this set my system time to sync with binance's server? Reading their api document it doesn't say that they use a specific ntp server. So the time may be managed by them.

So what if I also needed to sync with a different exchange's server while running both apps simultaneously? Maybe I misunderstood how that part of NTP works. Sorry for all the questions.

**Comment by fromjgor** [comment]
Thanks @Ptitlaby for useful example. I have tested it on my client and my results were different. 
Even if I got similar issue with 1sec delay while using candlesticks streaming:

Times : client[1516051832127] server[1516051833724] diff[1597]
Times : client[1516051833886] server[1516051834042] diff[156]
Times : client[1516051834189] server[1516051834349] diff[160]
Times : client[1516051834499] server[1516051834664] diff[165]
Times : client[1516051834812] server[1516051834973] diff[161]
Times : client[1516051835121] server[1516051835280] diff[159]
Times : client[1516051835428] server[1516051835583] diff[155]
Times : client[1516051835729] server[1516051835884] diff[155]
Times : client[1516051839406] server[1516051839572] diff[166]
...

**Comment by SungMinHong** [comment]
I just solve this problem using getServerTime() and gap time
for example

before
~~~
@Override
public Account getAccount() {
    return getAccount(BinanceApiConstants.DEFAULT_RECEIVING_WINDOW, System.currentTimeMillis());
}
~~~

after
~~~
  @Override
  public Account getAccount() {
	  long start = System.currentTimeMillis();
	  long serverTime = this.getServerTime();
	  long end = System.currentTimeMillis();
	  long gap = start - end; 
	  return getAccount(BinanceApiConstants.DEFAULT_RECEIVING_WINDOW, serverTime + gap);
  }
~~~

**Comment by joaopsilva** [comment]
Closing as this issue is only related to local machines with an unsynchronized clock. In any case, there's a workaround, as mentioned by @SungMinHong .
