### ISSUE TITLE
No data received by WebSocket after certain amount of time

### ISSUE THREAD

**Issue by MetalMiner** [binance-exchange/binance-java-api#81]
Hey guys,

is there a server-side timeout for the websocket client? It happens to me regularly that my client does not receive data anymore. When I restart it, it reads data again immediately.

Kind regards

**Comment by joaopsilva** [comment]
Hi @MetalMiner , yes, you need to call the `keepAlive` method to keep the session alive, please refer to https://github.com/binance-exchange/binance-java-api#start-user-data-stream-keepalive-and-close-data-stream for more info.

**Comment by MetalMiner** [comment]
Hi @joaopsilva , the `keepAlive` method refers to the RestClient:

`BinanceApiClientFactory factory = BinanceApiClientFactory.newInstance("API-KEY", "SECRET");
BinanceApiRestClient client = factory.newRestClient();
String listenKey = client.startUserDataStream();
client.keepAliveUserDataStream(listenKey);`

 Is it somehow related to the Websocketclient?:

 `BinanceApiWebSocketClient client = BinanceApiClientFactory.newInstance().newWebSocketClient();` 

I am trying to receive the `AllMarketTickerEvent`.

**Comment by MetalMiner** [comment]
Ok never mind, I got it :). Thanks for the quick response!

**Comment by tonyjayfunk** [comment]
Hi Joao,

In spite of the keep alive method firing every 30’ I kept receiving error messages ‘listen key doesn’t exist’. I think I’ll count the number of times the keep alive fails and restart the websocket in case of persistent failure. Any other idea? Best

**Comment by dimilicious** [comment]
Hi. keepAlive didn't solve the problem. Websocketclient keeps disconecting after some random period of time. Trying to call onAccountUpdate. It runs fine 15mins - 1 hour, then just dead without exceptions. Same for the Examples. 
Kind regards

**Comment by dimilicious** [comment]
Update. Followed this gide #133. The connection seems to be stable now. Thanks alot @nilswxa

**Comment by waeron** [comment]
Hi @dimilicious ,

I have the same issue with onAccountUpdate method. Connection is unstable for random time (15 - 60 minutes) and then disconnects without any exceptions. How do you resolve this issue?
I have latest version of binance-java-api library, even updated all relation libraries in pom. Nothing not helps.
