### ISSUE TITLE
BinanceApiException: API-key format invalid.

### ISSUE THREAD

**Issue by FuG** [binance-exchange/binance-java-api#88]
Hi there, I have been using this library for a couple of months now. Recently, although I'm not sure when (probably a couple of weeks ago), I've been unable to authenticate using the normal method of:

    BinanceApiClientFactory.newInstance("API KEY", "SECRET KEY");

I get this error:

    Exception in thread "main" com.binance.api.client.exception.BinanceApiException: API-key format invalid.
        at com.binance.api.client.impl.BinanceApiServiceGenerator.executeSync(BinanceApiServiceGenerator.java:57)
        at com.binance.api.client.impl.BinanceApiRestClientImpl.startUserDataStream(BinanceApiRestClientImpl.java:213)

Aside from pulling in this repo's changes, I had not changed anything remotely related to these classes whatsoever. I have also checked on Binance that my API key was still valid; it was. I generated a new api key anyways and that didn't help. I am completely stuck and would appreciate some help. Thanks!

EDIT: I have done 'mvn clean install' and that didn't help. The normal unauthenticated factory instance still works, I just can't get any user data from that.

**Comment by joaopsilva** [comment]
Hi @FuG , please double-check the values you are copying from Binance for the API-key, and make sure that pair is active.

**Comment by okieven** [comment]
Hi,
I'm facing exactly the same issue. I double checked key and secret and I also checked that the key is active. Any ideas on how to solve this issue?

**Comment by phuphamkdm** [comment]
I have the same issue. I anyone tell me how to fix it ?

**Comment by okieven** [comment]
Hi, 
my problem was that I was connecting with the same key multiple times in parallel. 
Did you check that keys are correct and you don't have any IP restrictions?

**Comment by mfatihdr** [comment]
Hello, yes problem was parallel connection, if you open on webpage or mobile with same account it gives error.

**Comment by senpaicryptos** [comment]
same issue: binance.exceptions.BinanceAPIException: APIError(code=-2014): API-key format invalid.

any suggestion?

**Comment by AxelRocha** [comment]
I don't know if thats what happend to those guys but i ran into the same problem and its was just a rookie mistake lol

I had created an enum class to hold my keys and then when I was instantiating the client I was doing
`Credentials.API_KEY.toString()`

But I didn't had override toString method...
I doubt that was the problem to them, but I hope its helps some noob dev like me haha

**Comment by 361Sepehr** [comment]
> 

how was solved??????

**Comment by eneszv** [comment]
Most likely API_KEY or SECRET_KEY are wrong or have the wrong format. I had the same problem because the keys were stored as environmental variables in the .env file with quotes
```
API_KEY="xxxxxxxxxxxxxxxx" 
```
and after removing quotes, it worked.
```
API_KEY=xxxxxxxxxxxxxxxx 
```
