### ISSUE TITLE
BinanceApiRestClient.getAllPrices() returns symbol "123456"

### ISSUE THREAD

**Issue by cowwoc** [binance-exchange/binance-java-api#9]
When I invoke `BinanceApiRestClient.getAllPrices()` most of the tickers I get back are okay, but I am consistently getting back:

  `TickerPrice[symbol=123456,price=0.00030000]`

which doesn't make any sense. Is this some sort of test data that someone forgot to remove?

I also see it if I request `HTTP GET https://www.binance.com/api/v1/ticker/allPrices` so this is affecting all clients.

**Comment by joaopsilva** [comment]
Thanks @cowwoc , I have asked the team to remove it from the internal API.

**Comment by cowwoc** [comment]
@joaopsilva Another problematic one is symbol `ETC`. It does not have a second currency.

**Comment by joaopsilva** [comment]
Thanks @cowwoc , I'm waiting for the team's feedback on this. In the meantime, I would propose to use a blacklist of assets to ignore.

**Comment by cowwoc** [comment]
@joaopsilva Good idea. Thanks for the feedback.

**Comment by ThingEngineer** [comment]
FYI, the symbol 123456 is still present in the exchange_data in the 5th symbol array. I thought my database model was corrupting a symbol.

... ),
    4 => 
    array (
      'symbol' => '123456',
      'status' => 'TRADING',
      'baseAsset' => '123',
      'baseAssetPrecision' => 8,
      'quoteAsset' => '456',
      'quotePrecision' => 8,
      'orderTypes' => 
      array (
        0 => 'LIMIT',
        1 => 'LIMIT_MAKER',
        2 => 'MARKET',
        3 => 'STOP_LOSS_LIMIT',
        4 => 'TAKE_PROFIT_LIMIT',
      ),
      'icebergAllowed' => true,
      'filters' => 
      array (
        0 => 
        array (
          'filterType' => 'PRICE_FILTER',
          'minPrice' => '0.00000100',
          'maxPrice' => '100000.00000000',
          'tickSize' => '0.00000100',
        ),
        1 => 
        array (
          'filterType' => 'LOT_SIZE',
          'minQty' => '0.00100000',
          'maxQty' => '100000.00000000',
          'stepSize' => '0.00100000',
        ),
        2 => 
        array (
          'filterType' => 'MIN_NOTIONAL',
          'minNotional' => '0.00100000',
        ),
      ),
    ), ...

**Comment by joaopsilva** [comment]
I'll close this ticket for now, there's not much I can do from the API side. I suggest to blacklist the `123456` trading pair.

**Comment by mcelhennyi** [comment]
This also happens for me in the get exchage info as well

**Comment by knap1930** [comment]
what is this 123456 symbol? if I call get orders for this symbol, I get back a ton of CANCELED orders...
