### ISSUE TITLE
The max rate limit for kline requests is set to 500, is that 500 per minute or 500 per hour?

### ISSUE THREAD

**Issue by ChrisK847** [binance-exchange/binance-java-api#90]
The max rate limit for kline requests is set to 500, is that 500 per minute or 500 per hour?

**Comment by joaopsilva** [comment]
Please refer to https://www.binance.com/api/v1/exchangeInfo and https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#enum-definitions. Current rate limit for requests is 1200/min.
