### ISSUE TITLE
BinanceApiWebSocketClient - does this work?

### ISSUE THREAD

**Issue by vladimirus** [binance-exchange/binance-java-api#92]
i am tring to use `onCandlestickEvent` but i don't get any exceptions and it seems to create websocket ok... but I dont receive any events?

**Comment by monkeyden** [comment]
I was recently able to get it to work, Vlad.  Can you post a bit of your code?  I had an issue with similar symptoms, when I had the symbol uppercase.

**Comment by joaopsilva** [comment]
Hi @vladimirus , it does, yes, please provide some more details about the code you are using. Thanks.

**Comment by vladimirus** [comment]
The code is quite simple: https://gist.github.com/vladimirus/a834c6569f2b0695135347cd3b78db0d

I am waiting for a long time (30 mins) but have no output nor exception

**Comment by vladimirus** [comment]
I found the problem, the pair ("NEOETH" in my case has to be lowercase) :)

**Comment by joaopsilva** [comment]
Great @vladimirus , yes, indeed, all symbols for streams are lowercase. This is stated in the docs (https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md), but it's not very obvious, perhaps I could lowercase automatically whatever argument is passed in the API.

**Comment by monkeyden** [comment]
FWIW, I got it from the examples.  I noticed the REST client uses uppercase and the WebSocket client uses lowercase.  Is that just a Binance API inconsistency?
https://github.com/binance-exchange/binance-java-api/blob/master/src/test/java/com/binance/api/examples/CandlesticksCacheExample.java
