### ISSUE TITLE
CandlestickEvent not receiving updated open & close times

### ISSUE THREAD

**Issue by monkeyden** [binance-exchange/binance-java-api#93]
First, thank you for developing this robust API.  It's very much appreciated.  

It seems the web socket listener isn't getting updated open and close times.  Just add an event listener using:
`client.onCandlestickEvent(symbol.toLowerCase(), CandlestickInterval.ONE_MINUTE, response -> myMethod(response));`

Let it run > 1m, printing response.getOpenTime() & response.getCloseTime() in myMethod(..).  It will only have the open and close of the initial candle but won't move to the next minute when the next candle starts.  response.getBarFinal() will also never return true.  Entirely possible that it's an issue with the Binance WebSocket API, Jackson, or I am simply misunderstanding the expected behavior.  If this is FAD, how to determine when the candle has closed?

Thanks

**Comment by monkeyden** [comment]
Hi fromjgor.  Sorry for the delay in response.  You are correct.  It was my misunderstanding.  The candle cache example shows aggregating web socket data by candle open, so I just needed to collect the data for the current candle to arrive at the final close price.  Thanks for responding.

**Comment by joaopsilva** [comment]
Hi @monkeyden , thank you for nice words, much appreciated. You can find an example on how to cache candlestick data at https://github.com/binance-exchange/binance-java-api/blob/master/src/test/java/com/binance/api/examples/CandlesticksCacheExample.java.

**Comment by monkeyden** [comment]
Yes, thats where I was able to find my answer.  Really great examples to get up and running quickly.
