### ISSUE TITLE
API not capable of multi-tenancy???

### ISSUE THREAD

**Issue by h-e-n-r-y** [binance-exchange/binance-java-api#99]
I am developing an application for different users each having different api keys.

When I create different clients with different api keys I always get clients that deliver data according to the first created client:

```
package de.hw4.binance.marketmaker.impl;

import org.junit.Assert;
import org.junit.Test;

import com.binance.api.client.BinanceApiClientFactory;
import com.binance.api.client.BinanceApiRestClient;


public class MultiApiKeyTest {
	
	@Test
	public void test2DifferentClients() {
		
		BinanceApiClientFactory factory1 = 
				BinanceApiClientFactory.newInstance(
						"insert your api-key#1", 
						"insert your secret#1");
	BinanceApiRestClient client1 = factory1.newRestClient();

	BinanceApiClientFactory factory2 = 
			BinanceApiClientFactory.newInstance(
					"insert your api-key#2 or even an invalid key will work!", 
					"insert your secret#2");
	BinanceApiRestClient client2 = factory2.newRestClient();
	
	int size1 = client1.getAccount().getBalances().size();
	
	// should throw a
	// BinanceApiException: API-key format invalid.
	int size2 = client2.getAccount().getBalances().size();
	
	Assert.assertNotEquals("two balances should not be equal!", size1, size2);


	}

}
```
client2 reveals data belonging to the api-key#1.

I guess this is a major bug! Or what am I doing wrong...

Henry

**Comment by h-e-n-r-y** [comment]
I guess the Problem is that com.binance.api.client.impl.BinanceApiServiceGenerator has only one static httpClient that accumulates the different AuthenticationInterceptors but then alway uses the first of them.

**Comment by tach1685** [comment]
You are right.  It is the static OkHttpClient.Builder variable in AlgoBinanceApiServiceGenerator.  As a test I've moved it into the createService method and then multi-tenancy works.

**Comment by joaopsilva** [comment]
It is now, please update your repo.

**Comment by conacyt-cgtic** [comment]
I have an InvocationTargetException at:
`	int size1 = client1.getAccount().getBalances().size(); `
When running the test code. Please explain why. 
No changes were made at all to the test code.
